CREATE DATABASE RAPNACIONAL

CREATE TABLE ARTISTAS (
	ID INTEGER IDENTITY (1,1) PRIMARY KEY ,
	NOME VARCHAR(200),
	ID_ALBUNS INTEGER FK**
)

CREATE TABLE ALBUNS(
	ID INTEGER IDENTITY (1,1) PRIMARY KEY ,
	NOME VARCHAR(200),
	ID_ARTISTA INTEGER FK**
	LANCAMENTO DATETIME,
	FAIXAS VARCHAR(MAX),
	DURACAO TIMESTAMP,
	GRAVADORA VARCHAR (500),
	CAPA VARCHAR (MAX)
)

CREATE TABLE MUSICAS